### ISSUE TITLE
Question: Deployed two machines in one app?

### ISSUE THREAD

**Issue by wnma3mz** [patte/fly-tailscale-exit#31]
Thank you for your project, it has been of great use to me.
But I have a confusion, I am not sure if it is a problem with my operation or the script itself.
When I follow the process to step 10 `flyctl deploy`, the platform shows two machines at the same time. This is shown in the image below:

![8P_GR@ RJY U6$8~U@LG 0](https://github.com/patte/fly-tailscale-exit/assets/23001152/529d6984-efc8-4297-af2b-f18e558a796b)

I made sure I didn't perform any additional operations. I checked the project's scripts and didn't find the problem either. Is there a way to start only one machine? Two machines in the same area seems a bit redundant.

**Comment by wnma3mz** [comment]
I did the following to shut down a machine.

```bash
# Check machine status
fly status
# Stop machine by machine id
fly machine stop $(machine_id)
# Destroy machine by machine id
fly machine destroy $(machine_id)
```

**Comment by patte** [comment]
Thank you @wnma3mz for bringing this up! You are right: since I wrote this README fly changed the default to 2 machines on initial deploy (which I think is the right default for production deploys). I updated the README to mention it: https://github.com/patte/fly-tailscale-exit/commit/7d36e75613448dc57380d837c744fa610dc97c32 and https://github.com/patte/fly-tailscale-exit/commit/5fea033dcaa85f009ad89110b780f731e090a1cc

**Comment by wnma3mz** [comment]
Thanks for the reply. But I'm still curious as to what I should do if I want to set only one machine to start by default. Or start three machines by default. I didn't find a place where I can configure it.
