### ISSUE TITLE
Failed due to unhealthy allocations

### ISSUE THREAD

**Issue by hemanth-narra** [patte/fly-tailscale-exit#7]
please tell me how to fix this 
You can detach the terminal anytime without stopping the deployment
==> Monitoring deployment

 1 desired, 1 placed, 0 healthy, 1 unhealthy
--> v0 failed - Failed due to unhealthy allocations and deploying as v1
Error logs 
2022-02-10T03:39:24.854 app[f483df71] maa [info] Starting init (commit: 0c50bff)...

2022-02-10T03:39:24.871 app[f483df71] maa [info] Preparing to run: `/app/start.sh` as root

2022-02-10T03:39:24.874 app[f483df71] maa [info] Error: UnhandledIoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

**Comment by bslatyer** [comment]
You need to fully deploy the Fly containers first and then you can close the terminal.

Looking at the error, did you run the script/app creation correctly?

**Comment by hemanth-narra** [comment]
@bslatyer I cloned this repository locally and changed the fly-template.toml to fly.toml and ran `flyctl launch --remote-only `
After fly-secrets are set 
I ran `flyctl deploy --remote-only` at last

**Comment by bslatyer** [comment]
@justforvpn I've just deployed the new v1.20.4 today to the same app I've been running for a couple of months now. It seems to work fine, but I'm using the local docker daemon instead of the remote one.

Can you try to run it like this `fly deploy` without the extra `--remote-only` flag as this might be the issue you're experiencing.
